= Create login page
:description: A description of the page stored in an HTML meta tag.
:sectanchors:
:url-repo: https://github.com/digita-ai/ui-transfer
:page-tags: name of a tag, name of a tag

.Author(s)

* Stijn Taelemans

.References

* https://www.figma.com/file/7G6VzJ3AKWFg7dJQ2AcLEd/Dapsi?node-id=3%3A0[Functional
analysis]
* Branch: `feature/589151527-create-start-login-page`

== Introduction

=== Overview

This component allows a `person`] to `authenticate` with itsme or similar services.

=== Out of scope

The actual authentication does not have to be implemented. +
Do not implement authentication via itsme or any other identity
provider. Clicking one of the authentication buttons simply navigates to
the next page.

=== Assumptions

https://www.wrike.com/open.htm?id=589151527[2.4.1.1 Create start landing
page] is finished. Needed for displaying the component in the root page,
which is created there.

== Solution

=== Suggested or proposed solution

==== Components

Generate all components under the app.module.ts. No need for different
modules per feature.

Any components or pages in Figma are designed for mobile. When
developing, use a window width of exactly 375px.

.AppStartLoginPageComponent

This page should contain no more than a title, a brief description and a
few buttons that bring you to the `AppStartConnectPageComponent`,
created in a later spec. +
The component on its own should look similar to this:

image::loginPage.svg[AppStartLoginPageComponent]

Generate the `AppStartLoginPageComponent` under `DAPSI/src/app/pages`
with filename and selector : `app-start-login-page`. The routing should
be configured in `app.module.ts`, path `'login'` should load the
`AppStartLoginPageComponent`. Set the routing with
`component: AppStartLoginPageComponent`.

Create the buttons with a heavily styled `mat-flat-button`. Since these
buttons will not be used anywhere else, there is no need to create a
seperate component for these. +
One button should look like this:

image::authenticateButton.svg[AuthenticateButton]

Align styling with
https://www.figma.com/file/7G6VzJ3AKWFg7dJQ2AcLEd/Dapsi?node-id=3%3A0[Figma].
See
link:589153533-create-start-login-page.md#####AppStartLoginPageComponent[screenshot]
above.

Unwanted Angular Material styling can be overwritten by using the
correct selector: use `.mat-flat-button` to overwrite the button’s
original styling.

Make sure you add https://github.com/ngx-translate/core[ngx-translate]
for all the labels (title and description in this case). +
Add
`import { TranslateModule, TranslateLoader } from '@ngx-translate/core';`
to the app module and follow the installation instructions on the github
page above.

Use the existing translation file at `src/translations/nl-BE.json` and
add translations for the title, subtitle and button descriptions.

* `app.pages.start-login-page.title`
* `app.pages.start-login-page.subtitle`
* `app.pages.start-login-page.btn-itsme`
* `app.pages.start-login-page.btn-idcard`
