== Create description page

*Author(s)*

* Stijn Taelemans

*References*

* https://www.figma.com/file/7G6VzJ3AKWFg7dJQ2AcLEd/Dapsi?node-id=4%3A698[Functional
analysis]
* Branch: `feature/589151527-create-start-description-page`

=== Introduction

==== Overview

This page gives a
https://github.com/digita-ai/dapsi-docs/tree/release/Specifications/Functional%20Specifications#personas[`person`]
the choice to either
https://github.com/digita-ai/dapsi-docs/tree/release/Specifications/Functional%20Specifications#definitions[`authenticate`]
using the
https://github.com/digita-ai/dapsi-docs/tree/release/Specifications/Functional%20Specifications#personas[`source`]’s
identity provider, or to connect by using the
https://github.com/digita-ai/dapsi-docs/tree/release/Specifications/Functional%20Specifications#definitions[`data browser`]’s
pod overview, which already has a connection with the pod’s identity
provider. The latter need not be implemented in this specification, as
it is part of the second flow.

==== Out of scope

The lower button activates the second flow. This flow is to be
implemented at a later date.

==== Assumptions

https://www.wrike.com/open.htm?id=589151527[2.4.1.1 Create start landing
page] is finished. Needed for displaying the component in the root page,
which is created there.

=== Solution

==== Suggested or proposed solution

===== Components

Generate all components under the app.module.ts. No need for different
modules per feature.

Any components or pages in Figma are designed for mobile. When
developing, use a window width of exactly 375px.

*AppStartDescriptionPageComponent*

This page, much like the `AppStartLandingPageComponent`, should contain
no more than a title, a brief description and a two buttons. The first
button navigates to the `AppConnectPageComponent`. The second button
activates an alternative flow that will be implemented later. This
button, currently, should do nothing. (navigate to `#') The component on
its own should look similar to this:

image::../../.gitbook/assets/descriptionpage.svg[AppStartDescriptionPageComponent]

Generate the `AppStartDescriptionPageComponent` under
`DAPSI/src/app/pages` with filename and selector :
`app-start-description-page`. The routing should be configured in
`app.module.ts`, path `'login/success'` should load the
`AppStartDescriptionPageComponent`. Make sure `pathMatch` is set to
`'full'` Set the routing with
`component: AppStartDescriptionPageComponent`.

The buttons should have the same styling as in the
`AppStartLandingPageComponent`.

Align styling with
https://www.figma.com/file/7G6VzJ3AKWFg7dJQ2AcLEd/Dapsi?node-id=4%3A698[Figma].
See
link:589153659-create-start-description-page.md#####AppStartDescriptionPageComponent[screenshot]
above.

Unwanted Angular Material styling can be overwritten by using the
correct selector: use `.mat-flat-button` to overwrite the button’s
original styling.

Make sure you add https://github.com/ngx-translate/core[ngx-translate]
for all the labels (title and description in this case). +
Add
`import { TranslateModule, TranslateLoader } from '@ngx-translate/core';`
to the app module and follow the installation instructions on the github
page above.

Use the existing translation file at `src/translations/nl-BE.json` and
add translations for the title, subtitle and button descriptions.

* `app.pages.start-description-page.title`
* `app.pages.start-description-page.subtitle`
* `app.pages.start-description-page.or`
* `app.pages.start-description-page.connect`
* `app.pages.start-description-page.open`
